#! /bin/sh

HOST=cidasdqaasaq2rd.cr.usgs.gov

aq2rdb () {
    curl -g "http://$HOST:8081/aq2rdb?$1"
}

endpoint () {
    curl -g "http://$HOST:8081/aq2rdb/$1?$2"
}

# if "stub" option
if [ "$1" = -s ]; then
    # start stub server
    node stub.js &
    stub=$!
fi

node ../aq2rdb.js &
aq2rdb=$!

if [ `hostname` = hemi ]; then
    # Sometimes necessary on systems where the Node.js scripts above
    # don't start fast enough:
    sleep 1s
fi

#aq2rdb "&userName=apiuser&password=$password&z=prod&t=dv&u=Discharge.ft^3/s.Mean@09380000&b=20150101&e=20150103"
#echo
#endpoint GetDVTable "&timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000"
#echo
#endpoint GetDVTable "&shahDoobie=Discharge.ft^3/s.Mean@09380000"
#echo
#endpoint GetDVTable "&timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000&computed=trued"
#echo
#endpoint GetDVTable "&userName=apiuser&password=not4passwurd&timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000&computed=true"
#echo
#endpoint GetDVTable "&userName=apiuser&password=$password&LocationIdentifier=09380000&Parameter=Discharge&QueryFrom=2015-01-01T00%3A00%3A00-07%3A00&QueryTo=2015-01-03T00%3A00%3A00-07%3A00"
echo
endpoint GetDVTable "&userName=apiuser&password=$password&LocationIdentifier=01010000&Parameter=Discharge&QueryFrom=1996-01-01T00%3A00%3A00-07%3A00&QueryTo=1997-01-01T00%3A00%3A00-07%3A00"

kill $aq2rdb

if [ "$1" = -s ]; then
    kill $stub
fi
