#! /bin/sh

aq2rdb () {
    curl -g "http://localhost:8081/aq2rdb?$1"
    echo
}

GetDVTable () {
    curl -g "http://localhost:8081/aq2rdb/GetDVTable?$1"
    echo
}

# if "stub" option
if [ "$1" = -s ]; then
    # start stub server
    node stub.js &
    stub=$!
fi

node ../aq2rdb.js &
aq2rdb=$!

if [ `hostname` = hemi ]; then
    # Sometimes necessary on systems where the Node.js scripts above
    # don't start fast enough:
    sleep 1s
fi

aq2rdb "&userName=apiuser&password=$password&z=prod&u=Discharge.ft^3/s.Mean@09380000&b=20150101&e=20150103"

#GetDVTable "&timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000"

#GetDVTable "&shahDoobie=Discharge.ft^3/s.Mean@09380000"

#GetDVTable "&timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000&computed=trued"

#GetDVTable "&userName=apiuser&password=not4passwurd&timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000&computed=true"

#GetDVTable "&userName=apiuser&password=$password&LocationIdentifier=09380000&Parameter=Discharge&QueryFrom=2015-01-01T00%3A00%3A00-07%3A00&QueryTo=2015-01-03T00%3A00%3A00-07%3A00"

kill $aq2rdb

if [ "$1" = -s ]; then
    kill $stub
fi
