#! /bin/sh
#
# File - harness
#
# Purpose - Test harness for aq2rdb Web service.
#
# Author - Andy Halper <ashalper@usgs.gov>
#

aq2rdb () {
    curl -g "http://$HOST:8081/aq2rdb?$1"
}

endpoint () {
    echo "curl -g http://$HOST:8081/aq2rdb/$1?$2"
    curl -g "http://$HOST:8081/aq2rdb/$1?$2"
}

# if "localhost" option
if [ "$1" = -l ]; then
    HOST=localhost
else
    HOST=cidasdqaasaq2rd.cr.usgs.gov
fi

# if "stub" option
if [ "$1" = -s ]; then
    # start stub server
    node stub.js &
    stub=$!
fi

endpoint GetDVTable "timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000"
echo
endpoint GetDVTable "shahDoobie=Discharge.ft^3/s.Mean@09380000"
echo
endpoint GetDVTable "timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000&computed=trued"
echo
endpoint GetDVTable "timeSeriesIdentifier=Discharge.ft^3/s.Mean@09380000&computed=true"
echo
endpoint GetDVTable "LocationIdentifier=09380000&Parameter=Discharge&QueryFrom=2015-01-01T00%3A00%3A00-07%3A00&QueryTo=2015-01-03T00%3A00%3A00-07%3A00"
echo
endpoint GetDVTable "LocationIdentifier=09380000&QueryFrom=2015-01-01T00%3A00%3A00-07%3A00&QueryTo=2015-01-03T00%3A00%3A00-07%3A00"
echo
endpoint GetDVTable "LocationIdentifier=01010000&Parameter=Discharge&QueryFrom=1995-12-31T00%3A00%3A00-07%3A00&QueryTo=1996-12-31T00%3A00%3A00-07%3A00"

if [ "$1" = -l ]; then
    kill $aq2rdb
fi

if [ "$1" = -s ]; then
    kill $stub
fi
