#! /usr/bin/python
#
#  File - aq2rdb-passwd
#
#  Purpose - Initialize aq2rdb password file.
#
#  Author - Andy Halper <ashalper@usgs.gov>
#

import os
from subprocess import check_output, CalledProcessError
import json

# if there is an encrypted volume, this is where we expect to find it
device = "/dev/mapper/CryptedPart1"

DEVNULL = open(os.devnull, 'w')

try:
    df = check_output(["df", device], stderr=DEVNULL)
    print df.output
    if df.returncode == 0:
        with open("aq2rdb-passwd.json", 'w') as f:
            json.dump(
                {"aquariusUserName": "apiuser",
                 "aquariusPassword": "Not a password",
                 "waterDataUserName": "hswsh",
                 "waterDataPassword": "Also not a password"},
                f
            )
except CalledProcessError as e:
    print "I could not find the encrypted device at " + device

DEVNULL.close()
