#! /bin/sh
#
#  File - configure-ec2
#
#  Purpose - (Re-)configure an AWS EC2 instance as needed until we ascend the
#            AMI learning curve.
#
#  Author - Andy Halper <ashalper@usgs.gov>
#

# additional packages that don't come with the vanilla OWI CentOS
# template
yum -y install emacs npm nodejs lynx ruby wget \
    http://s3.amazonaws.com/ec2-downloads/ec2-ami-tools.noarch.rpm

# installation directories and groups
mkdir -p -m 700 /usr/local/lib/aquarius-token /usr/local/lib/aq2rdb
groupadd owi
chgrp owi /usr/local/lib/aquarius-token /usr/local/lib/aq2rdb

# add ec2-user to owi group
usermod -a -G owi ec2-user

# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-instance-store.html#creating-ami-linux-instance
mkdir /tmp/cert && chmod 771 /tmp/cert && chown ec2-user /tmp/cert && \
    chgrp ec2-user /tmp/cert
