#! /bin/sh
#
#  File - npmbuild
#
#  Purpose - Install prerequisite npm packages (see
#            https://www.npmjs.com/) for aq2rdb.
#
#  Author - Andrew Halper <ashalper@usgs.gov>
#
npm install async httpdispatcher moment-timezone querystring
