#! /bin/sh
#
# File - npmbuild
#
# Purpose - Convenience shell script to build aq2rdb npm.
#
# Author - Andrew Halper <ashalper@usgs.gov>
#

# read version from package.json
version=`grep '"version":' package.json | \
    sed 's/[[:space:]]*"version":[[:space:]]*"\(.*\)".*/\1/'`

# make directory references below shorter
d=aq2rdb

files="$d/*.js $d/doc/* $d/*.md $d/*.json $d/bin/init-passwd $d/init.d/aq2rdb"

# make npm tarball
(cd .. && chmod 644 $files && tar -cvzf $d/aq2rdb-$version.tar.gz $files)
