#! /bin/sh

node aq2rdb.js &		# start service
curl "http://localhost:8081/aq2rdb?&Username=apiuser&Password=$Password&z=prod&t=uv"
#curl \
#    "http://localhost:8081/aq2rdb?&Username=apiuser&Password=$Password\
#&z=prod&t=uv&a=USPS&n=09471550"
kill $!
