#! /bin/bash
#
# File - aq2rdb
#
# Purpose - init script to aq2rdb Web service.
#
# Author - Andy Halper <ashalper@usgs.gov>
#

aq2rdb_home=/usr/local/lib/node_modules/aq2rdb

# run as nodejs user
cd $aq2rdb_home && /usr/bin/sudo -u nodejs -H -- \
    /usr/local/lib64/node-v4.2.6-linux-x64/bin/node \
    $aq2rdb_home/aq2rdb.js
