#! /bin/bash
#
# File - aq2rdb
#
# Purpose - init script to aq2rdb Web service.
#
# Author - Andy Halper <ashalper@usgs.gov>
#

# run as nodejs user
/usr/bin/sudo -u nodejs -H -- \
    /usr/local/lib64/node-v4.2.6-linux-x64/bin/node \
    /usr/local/lib/node_modules/aq2rdb/aq2rdb.js "$@"
